### ISSUE TITLE
JUnitAssertThrows assumes incorrect arity

### ISSUE THREAD

**Issue by zentol** [slinkydeveloper/assertj-migrator#1]
assertThrows also has a variant accepting 3 arguments.
https://junit.org/junit4/javadoc/4.13/org/junit/Assert.html#assertThrows(java.lang.String,%20java.lang.Class,%20org.junit.function.ThrowingRunnable)

This results in the runnable being dropped.

**Comment by slinkydeveloper** [comment]
Can you give me an example?

I have a test for that case and it's passing: https://github.com/slinkydeveloper/assertj-migrator/blob/master/src/test/resources/migrations/JUnit4MigrationTestCases.java#L269

**Comment by zentol** [comment]
https://github.com/apache/flink/pull/19039#discussion_r823822823

**Comment by zentol** [comment]
~~What does your migration cases actually check for? That it retains the original semantics, or just that it compiles?~~

**Comment by slinkydeveloper** [comment]
@zentol it sounds like this particular case is hitting the situation where the type inference doesn't properly infer the method signature. To be conservative, I added an exception so it will block migration for that specific file, rather than creating an invalid migration: https://github.com/slinkydeveloper/assertj-migrator/blob/master/src/main/java/com/slinkydeveloper/assertjmigrator/migrations/junit/BaseJUnitAssertion.java#L90
